<?php
return array (
  'app' => 'Admin',
  'model' => 'Import',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '工资管理',
  'icon' => 'rmb',
  'remark' => '',
  'listorder' => '60',
  'children' => 
  array (
    array (
      'app' => 'Admin',
      'model' => 'Import',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '工资条管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Import',
          'action' => 'upfile',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '数据导入',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Import',
          'action' => 'upload',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '导入保存',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Import',
          'action' => 'detail',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '查看明细',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Import',
          'action' => 'sendnotice',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '发放通知',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Import',
          'action' => 'delete',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '删除导入文件',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Member',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '员工管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Member',
          'action' => 'edit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '审核员工',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Member',
          'action' => 'delete',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '删除员工',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Member',
          'action' => 'edit_post',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '编辑保存',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
  ),
);