<?php
return array (
  'app' => 'Admin',
  'model' => 'Extension',
  'action' => 'default',
  'data' => '',
  'type' => '0',
  'status' => '0',
  'name' => '扩展工具',
  'icon' => 'cloud',
  'remark' => '',
  'listorder' => '40',
  'children' => 
  array (
    array (
      'app' => 'Admin',
      'model' => 'Plugin',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '插件管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Plugin',
          'action' => 'toggle',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '插件启用切换',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Plugin',
          'action' => 'setting',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '插件设置',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Plugin',
              'action' => 'setting_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '插件设置提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Plugin',
          'action' => 'install',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '插件安装',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Plugin',
          'action' => 'uninstall',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '插件卸载',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Plugin',
          'action' => 'update',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '插件更新',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Storage',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '文件存储',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Storage',
          'action' => 'setting_post',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '文件存储设置提交',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Api',
      'model' => 'Oauthadmin',
      'action' => 'setting',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '第三方登陆',
      'icon' => 'leaf',
      'remark' => '',
      'listorder' => '4',
      'children' => 
      array (
        array (
          'app' => 'Api',
          'model' => 'Oauthadmin',
          'action' => 'setting_post',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '提交设置',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
  ),
);