<?php
return array (
  'app' => 'Admin',
  'model' => 'Hotel',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '酒店管理',
  'icon' => 'home',
  'remark' => '',
  'listorder' => '25',
  'children' => 
  array (
    array (
      'app' => 'Admin',
      'model' => 'Hotel',
      'action' => 'fxindex',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '房型管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'fxadd',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '添加房型',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'fxadd_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'rpindex',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '房型RP列表',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'rpadd',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加客房产品规则',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'rpadd_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'rpedit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '编辑RP房型',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'rpedit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'delete',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '下线',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'fxedit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '编辑房型',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'fxedit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'fjindex',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '房价管理',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'fjedit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '房价修改',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'fjedit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '保存',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'fledit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '房量修改',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'fledit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '更新',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Hotel',
      'action' => 'ctindex',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '餐厅管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'ctadd',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '添加餐厅',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'ctadd_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'ctedit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '编辑餐厅',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'ctedit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'bjindex',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '包间管理',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'bjadd',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加包间',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'bjedit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '编辑包间',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'bjedit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'bjadd_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'bjdelete',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '删除',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'isdel',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '删除',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'cpindex',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '菜品管理',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'cpadd',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加菜品',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'cpadd_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'cpedit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '编辑菜品',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'cpedit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'cpdelete',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '删除',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Hotel',
      'action' => 'hyyhindex',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '会议宴会管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'hyyhadd',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '添加宴会厅',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'hyyhadd_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'hyyhedit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '编辑宴会厅',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'hyyhedit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'hyyhstatus',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '不可预约',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'hyyhdelete',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '删除',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Hotel',
      'action' => 'xyylindex',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '休闲娱乐管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'xyyladd',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '添加娱乐场所',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'xyyladd_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'xyyledit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '编辑娱乐场所',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'xyyledit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'xyylissupper',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '不可预定',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'xyyldelete',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '删除',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'ylxmindex',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '娱乐项目管理',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'ylxmadd',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加项目',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'ylxmadd_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'ylxmedit',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '编辑娱乐项目',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'ylxmedit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'ylxmdelete',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '删除',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Hotel',
      'action' => 'photo',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '酒店相册',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'photoindex',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '相册分类',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'photodelete',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '删除',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'phototype',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '添加相册分类',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'photo_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'photoadd',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '添加图片',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'photoadd_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '添加',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'photoedit',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '编辑图片',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'photoedit_post',
              'data' => '',
              'type' => '1',
              'status' => '0',
              'name' => '提交',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'picdelete',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '删除图片',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Hotel',
      'action' => 'info',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '酒店信息',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'info_post',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '添加',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Hotel',
      'action' => 'recommend',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '总经理推荐',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'recommend_post',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '总经理推荐',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Hotel',
      'action' => 'nearinfo',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '周边指南',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
      'children' => 
      array (
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'infodelete',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '删除',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
        ),
        array (
          'app' => 'Admin',
          'model' => 'Hotel',
          'action' => 'nearadd',
          'data' => '',
          'type' => '1',
          'status' => '0',
          'name' => '添加商圈',
          'icon' => '',
          'remark' => '',
          'listorder' => '0',
          'children' => 
          array (
            array (
              'app' => 'Admin',
              'model' => 'Hotel',
              'action' => 'nearadd_psot',
              'data' => '',
              'type' => '1',
              'status' => '1',
              'name' => '添加',
              'icon' => '',
              'remark' => '',
              'listorder' => '0',
            ),
          ),
        ),
      ),
    ),
    array (
      'app' => 'Admin',
      'model' => 'Hotel',
      'action' => 'contact',
      'data' => '',
      'type' => '0',
      'status' => '1',
      'name' => '网页留言',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);